name: "Submodules Sync"

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit hash"
        required: true

jobs:
  sync:
    name: "Submodules Sync"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Create branch name
        id: branch-name-step
        run: echo '::set-output name=BRANCH_NAME::${${{ github.event.inputs.commit }}:0:10}'

      - name: Create new branch and push changes
        shell: bash
        run: |
          git config --global user.name 'Submodule update bot'
          git config --global user.email 'bot@noreply.github.com'
          git checkout -b ${{ steps.branch-name-step.outputs.BRANCH_NAME }}
          git commit -am "Auto updated submodule references ${{ steps.branch-name-step.outputs.BRANCH_NAME }}" && git push --set-upstream origin ${{ steps.branch-name-step.outputs.BRANCH_NAME }}  || echo "No changes to commit"

      - name: Create pull request against target branch
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.CI_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            await github.rest.pulls.create({
              owner,
              repo,
              head: '${{ steps.branch-name-step.outputs.BRANCH_NAME }}',
              base: 'main',
              title: `[Auto-generated] Submodule Updates`,
              body: `[Auto-generated] Submodule Updates`,
            });
